name:                wildptr-haskell
version:             0.1.0.0
github:              "charpointer/wildptr-haskell"
license:             BSD3
author:              "charpointer"
maintainer:          "char@uwu.com"
copyright:           "2021 charpointer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/wildptr-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- utf8-string
- aeson

library:
  source-dirs: src

executables:
  wildptr-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wildptr-haskell

tests:
  wildptr-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wildptr-haskell
